name: micropolis_assessment
description: "Micropolis Robotics Assessment."


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  injectable: ^2.5.2
  flutter_screenutil: ^5.9.3
  dio: ^5.8.0+1
  go_router: ^16.0.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  easy_localization: ^3.0.7+1
  google_fonts: ^6.2.1
  internet_connection_checker: ^3.0.1
  skeletonizer: ^2.1.0+1
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  timeago: ^3.7.1
  image_picker: ^1.2.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.9.0
  build_runner: ^2.10.1
  pretty_dio_logger: ^1.4.0
  logger: ^2.6.2

flutter_gen:
  output: lib/core/presentation/resources/
  line_length: 80
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/translations/



